Globs:
  - '**/*.cr'
  - '!lib'
  - '!tmp'

Lint/Formatting:
  Enabled: false

Layout/LineLength:
  Enabled: true
  MaxLength: 110

Style/GuardClause:
  Enabled: true

Style/CallParentheses:
  Enabled: true

Style/LargeNumbers:
  Enabled: true

Typing/MethodReturnTypeRestriction:
  Enabled: true
